version: '3.8'
services:
  mailcrab:
    image: marlonb/mailcrab:latest
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP
    networks:
      - test-network

  email-test:
    build: .
    environment:
      - MAILCRAB_HOST=mailcrab
      - MAILCRAB_SMTP_HOST=mailcrab
      - MAILCRAB_SMTP_PORT=1025
    depends_on:
      - mailcrab
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
