name: Email Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mailcrab:
        image: marlonb/mailcrab:latest
        ports:
          - 1025:1025
          - 1080:1080
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://mailcrab:1080/api/messages || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run email tests
        run: node test-email.js
        env:
          MAILCRAB_SMTP_HOST: localhost
          MAILCRAB_HOST: localhost
          MAILCRAB_SMTP_PORT: 1025